# Generated by Django 4.1.2 on 2022-10-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
