# Generated by Django 4.1.2 on 2022-10-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0002_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('idservice', models.IntegerField(db_column='idService', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=64)),
                ('user_email', models.CharField(max_length=64, unique=True)),
                ('user_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('iduserservice', models.AutoField(db_column='idUserService', primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('id_service', models.ForeignKey(db_column='id_service', on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.services')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.user')),
            ],
        ),
    ]
